language: java
jdk:
- oraclejdk8
- openjdk8
dist: trusty
before_install:
- chmod +x demo/mvnw
- chmod +x other_demo/mvnw

script:
  - mvn -q -B -f demo/pom.xml clean test
  - mvn -q -B -f other_demo/pom.xml clean test